services:
  # ==========================================
  # Infrastructure
  # ==========================================
  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    container_name: bike_rental_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - bike-rental-network

  createbuckets:
    image: minio/mc
    container_name: bike_rental_minio_buckets
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadminpassword;
      /usr/bin/mc mb myminio/bike-rental-bucket;
      /usr/bin/mc anonymous set public myminio/bike-rental-bucket;
      exit 0;
      "
    networks:
      - bike-rental-network

  # ==========================================
  # Microservices
  # ==========================================
  auth-service:
    build:
      context: ./backend/auth-service
    ports:
      - "8081:8080"
    networks:
      - bike-rental-network
    environment:
      CAPTCHA_SECRET_KEY: 0x4AAAAAAEEE9DRWs321deQbBrBioIkJrIg

  customer-service:
    build:
      context: ./backend/customer-service
    ports:
      - "8082:8080"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8080
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadminpassword
    depends_on:
      - auth-service
      - minio
    networks:
      - bike-rental-network

  partner-service:
    build:
      context: ./backend/partner-service
    ports:
      - "8083:8080"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadminpassword
    depends_on:
      - auth-service
      - minio
    networks:
      - bike-rental-network

  bike-service:
    build:
      context: ./backend/bike-service
    ports:
      - "8084:8080"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8080
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadminpassword
    depends_on:
      - auth-service
      - minio
    networks:
      - bike-rental-network

  booking-service:
    build: ./backend/booking-service
    container_name: booking-service
    ports:
      - "8085:8085"
    environment:
      ASPNETCORE_URLS: http://+:8085
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - bike-rental-network

  api-gateway:
    build:
      context: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - customer-service
      - partner-service
      - bike-service
      - booking-service
      - minio
    networks:
      - bike-rental-network

# ==========================================
# Shared Volumes & Networks
# ==========================================
volumes:
  minio_data:

networks:
  bike-rental-network:
    driver: bridge
