spring.application.name=customer-service

server.port=8082

spring.datasource.url=jdbc:postgresql://ep-weathered-tree-aw0l115f.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YP28TBgenFaZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.repair-on-migrate=true

minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadminpassword
minio.bucket-name=bike-rental-bucket

jwt.secret=mySuperSecretKeyForBikeRentalApplicationAuthentication123456789
jwt.expiration=86400000

server.port=8082

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html