spring.application.name=auth-service

# Neon Database
spring.datasource.url=jdbc:postgresql://ep-blue-darkness-awk8w20b.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YP28TBgenFaZ
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect