spring.application.name=partner-service

server.port=8083

spring.datasource.url=jdbc:postgresql://ep-blue-tooth-aw5m2p6b-pooler.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YP28TBgenFaZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

minio.bucket-name=bike-rental-bucket
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadminpassword}

minio.internal-url=${MINIO_URL:http://minio:9000}
minio.public-url=http://localhost:9000

# Jwt secret
jwt.secret=mySuperSecretKeyForBikeRentalApplicationAuthentication123456789
jwt.expiration=86400000

# swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

auth.service.url=${AUTH_SERVICE_URL:http://auth-service:8081}