// <auto-generated />
using System;
using Booking.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace booking_service.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260730153756_InitialBookingSchema")]
    partial class InitialBookingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Booking.Api.Domain.Entities.BikeBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime?>("ActualReturnTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("actual_return_time");

                    b.Property<int>("BikeId")
                        .HasColumnType("integer")
                        .HasColumnName("bike_id");

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("booking_ref");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("booking_status");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancel_reason");

                    b.Property<decimal?>("CancellationPenalty")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cancellation_penalty");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("PartnerId")
                        .HasColumnType("integer")
                        .HasColumnName("partner_id");

                    b.Property<string>("PaymentRef")
                        .HasColumnType("text")
                        .HasColumnName("payment_ref");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_status");

                    b.Property<DateTime>("PickupDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("pickup_date_time");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("refund_amount");

                    b.Property<DateTime>("ScheduledReturnDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled_return_date_time");

                    b.Property<decimal?>("SecurityDepositAmount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("security_deposit_amount");

                    b.Property<string>("SecurityDepositStatus")
                        .HasColumnType("text")
                        .HasColumnName("security_deposit_status");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("settled_at");

                    b.Property<DateTime?>("SettlementDueAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("settlement_due_at");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("booking_customer_idx");

                    b.HasIndex("PartnerId")
                        .HasDatabaseName("booking_partner_idx");

                    b.HasIndex("SecurityDepositStatus")
                        .HasDatabaseName("booking_deposit_status_idx");

                    b.ToTable("bike_booking_details", (string)null);
                });

            modelBuilder.Entity("Booking.Api.Domain.Entities.DepositDeduction", b =>
                {
                    b.Property<int>("DeductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("deduction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeductionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisputeReason")
                        .HasColumnType("text")
                        .HasColumnName("dispute_reason");

                    b.Property<DateTime?>("DisputedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("disputed_at");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text")
                        .HasColumnName("document_url");

                    b.Property<int?>("RecordedBy")
                        .HasColumnType("integer")
                        .HasColumnName("recorded_by");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("integer")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("DeductionId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("deduction_booking_idx");

                    b.HasIndex("Status")
                        .HasDatabaseName("deduction_status_idx");

                    b.ToTable("deposit_deduction", (string)null);
                });

            modelBuilder.Entity("Booking.Api.Domain.Entities.DepositDeduction", b =>
                {
                    b.HasOne("Booking.Api.Domain.Entities.BikeBooking", "Booking")
                        .WithMany("Deductions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Booking.Api.Domain.Entities.BikeBooking", b =>
                {
                    b.Navigation("Deductions");
                });
#pragma warning restore 612, 618
        }
    }
}
