spring.application.name=admin-service

server.port=8086

spring.datasource.url=jdbc:postgresql://ep-weathered-tree-aw0l115f.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YP28TBgenFaZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate


customer.service.url=${CUSTOMER_SERVICE_URL:customer-service:8082}
auth.service.url=${AUTH_SERVICE_URL:auth-service:8081}


minio.internal-url=http://minio:9000
minio.public-url=http://localhost:9000

jwt.secret=mySuperSecretKeyForBikeRentalApplicationAuthentication123456789
jwt.expiration=86400000

# swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


minio.bucket-name=bike-rental-bucket
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:admin}
minio.secret-key=${MINIO_SECRET_KEY:password123}