server.port=8080
spring.application.name=api-gateway

# =====================================================
# Business API Routes
# =====================================================

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**,/api/v1/internal/**

# Customer Service
spring.cloud.gateway.server.webflux.routes[1].id=customer-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://customer-service:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/customers/**,/api/v1/internal/customers/**

# Partner Service
spring.cloud.gateway.server.webflux.routes[2].id=partner-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://partner-service:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/partners/**

# Bike Service
spring.cloud.gateway.server.webflux.routes[3].id=bike-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://bike-service:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/bikes/**

#Booking Service
spring.cloud.gateway.server.webflux.routes[4].id=booking-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://booking-service:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/bookings/**


# Admin Service
spring.cloud.gateway.server.webflux.routes[10].id=admin-service
spring.cloud.gateway.server.webflux.routes[10].uri=http://admin-service:8086
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/v1/admin/**

# =====================================================
# Swagger API Docs Routes
# =====================================================

# Auth
spring.cloud.gateway.server.webflux.routes[5].id=auth-docs
spring.cloud.gateway.server.webflux.routes[5].uri=http://auth-service:8081
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/auth/v3/api-docs
spring.cloud.gateway.server.webflux.routes[5].filters[0]=RewritePath=/auth/v3/api-docs,/v3/api-docs

# Customer
spring.cloud.gateway.server.webflux.routes[6].id=customer-docs
spring.cloud.gateway.server.webflux.routes[6].uri=http://customer-service:8082
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/customer/v3/api-docs
spring.cloud.gateway.server.webflux.routes[6].filters[0]=RewritePath=/customer/v3/api-docs,/v3/api-docs

# Partner
spring.cloud.gateway.server.webflux.routes[7].id=partner-docs
spring.cloud.gateway.server.webflux.routes[7].uri=http://partner-service:8083
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/partner/v3/api-docs
spring.cloud.gateway.server.webflux.routes[7].filters[0]=RewritePath=/partner/v3/api-docs,/v3/api-docs

# Bike
spring.cloud.gateway.server.webflux.routes[8].id=bike-docs
spring.cloud.gateway.server.webflux.routes[8].uri=http://bike-service:8084
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/bikes/v3/api-docs
spring.cloud.gateway.server.webflux.routes[8].filters[0]=RewritePath=/bikes/v3/api-docs,/v3/api-docs


# Booking 
spring.cloud.gateway.server.webflux.routes[9].id=booking-docs
spring.cloud.gateway.server.webflux.routes[9].uri=http://booking-service:8085
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/booking/v3/api-docs
spring.cloud.gateway.server.webflux.routes[9].filters[0]=RewritePath=/booking/v3/api-docs,/swagger/v1/swagger.json

# Admin Docs
spring.cloud.gateway.server.webflux.routes[11].id=admin-docs
spring.cloud.gateway.server.webflux.routes[11].uri=http://admin-service:8086
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/admin/v3/api-docs
spring.cloud.gateway.server.webflux.routes[11].filters[0]=RewritePath=/admin/v3/api-docs,/v3/api-docs




# =====================================================
# Swagger UI
# =====================================================

springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=Customer Service
springdoc.swagger-ui.urls[1].url=/customer/v3/api-docs

springdoc.swagger-ui.urls[2].name=Partner Service
springdoc.swagger-ui.urls[2].url=/partner/v3/api-docs

springdoc.swagger-ui.urls[3].name=Bike Service
springdoc.swagger-ui.urls[3].url=/bikes/v3/api-docs

springdoc.swagger-ui.urls[4].name=Booking Service
springdoc.swagger-ui.urls[4].url=/booking/v3/api-docs

springdoc.swagger-ui.urls[5].name=Admin Service
springdoc.swagger-ui.urls[5].url=/admin/v3/api-docs

# =====================================================
# Global CORS
# =====================================================

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true

# =====================================================
# Actuator
# =====================================================

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true


# =====================================================
# MinIO Storage Proxy
# =====================================================

spring.cloud.gateway.server.webflux.routes[12].id=minio-storage
spring.cloud.gateway.server.webflux.routes[12].uri=http://minio:9000
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/storage/**
spring.cloud.gateway.server.webflux.routes[12].filters[0]=RewritePath=/storage/(?<segment>.*), /${segment}

minio.bucket-name=bike-rental-bucket
minio.url=${MINIO_URL:http://minio:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadminpassword}
