spring.application.name=schema-migration-service

# Neon Direct Connection
spring.datasource.url=jdbc:postgresql://ep-weathered-tree-aw0l115f.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YP28TBgenFaZ
spring.datasource.driver-class-name=org.postgresql.Driver

# Explicitly set HikariCP driver class
spring.datasource.hikari.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

# Prevent Hibernate / JPA startup checks
spring.jpa.hibernate.ddl-auto=none